### ISSUE TITLE
Add a License to Clarify Usage

### ISSUE THREAD

**Issue by erikinfo** [NYU-LLM-CTF/llm_ctf_automation#17]
Hello, 

First, thank you for creating and sharing this project! It's evident that a lot of thought and effort has gone into it, and it has the potential to be incredibly useful for developers and the community.

I noticed that the repository currently doesn’t have a license specified. Adding an open-source license, such as the MIT License, could make it easier for others to contribute, use, and build upon your work while respecting your terms.

Would you consider adding one? Same applies for e.g. the CTF Benchmark.

Thank you. 

@udiboy1209 @NickNameInvalid

**Comment by NickNameInvalid** [comment]
Dear erikinfo,

Thanks a lot for your question, we have added a MIT license for this repository.
